# Generated by Django 4.1.4 on 2022-12-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=255)),
                ('document', models.BinaryField()),
            ],
            options={
                'verbose_name_plural': 'purchase documents',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_url', models.URLField()),
                ('vendor_credentials', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('po_number', models.ForeignKey(blank=True, db_column='po_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='hubuum.purchasedocuments')),
                ('vendor', models.ForeignKey(blank=True, db_column='vendor', null=True, on_delete=django.db.models.deletion.CASCADE, to='hubuum.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='purchasedocuments',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubuum.purchaseorder'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('section', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.ForeignKey(blank=True, db_column='room', null=True, on_delete=django.db.models.deletion.CASCADE, to='hubuum.room')),
            ],
        ),
        migrations.CreateModel(
            name='Jack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.ForeignKey(blank=True, db_column='room', null=True, on_delete=django.db.models.deletion.CASCADE, to='hubuum.room')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('manual_serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('jack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubuum.jack')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubuum.purchaseorder')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubuum.room')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubuum.hosttype')),
            ],
        ),
        migrations.CreateModel(
            name='DetectedHostData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mac', models.CharField(blank=True, max_length=20, null=True)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('arch', models.CharField(blank=True, max_length=10, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=20, null=True)),
                ('os_major_version', models.SmallIntegerField(blank=True, null=True)),
                ('os_minor_version', models.SmallIntegerField(blank=True, null=True)),
                ('os_patch_version', models.SmallIntegerField(blank=True, null=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('switch', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(blank=True, max_length=30, null=True)),
                ('display', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_user', models.CharField(blank=True, max_length=50, null=True)),
                ('host_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hubuum.host', verbose_name='Host identifier')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hubuum.externalsource')),
            ],
            options={
                'verbose_name_plural': 'detected host Data',
            },
        ),
        migrations.AddConstraint(
            model_name='detectedhostdata',
            constraint=models.UniqueConstraint(fields=('host_id', 'source'), name='host_id_and_source_combination'),
        ),
    ]
