# Generated by Django 4.1.5 on 2023-01-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseDocuments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.CharField(max_length=255)),
                ("document", models.BinaryField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchasedocuments",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "purchase documents",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=255)),
                ("vendor_url", models.URLField()),
                (
                    "vendor_credentials",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vendors",
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(max_length=255)),
                ("building", models.CharField(blank=True, max_length=255, null=True)),
                ("floor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="rooms",
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchaseorders",
                        to="auth.group",
                    ),
                ),
                (
                    "po_number",
                    models.ForeignKey(
                        blank=True,
                        db_column="po_number",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubuum.purchasedocuments",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        db_column="vendor",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubuum.vendor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="purchasedocuments",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hubuum.purchaseorder"
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("section", models.IntegerField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "office_phone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="persons",
                        to="auth.group",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        db_column="room",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubuum.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("building", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="jacks",
                        to="auth.group",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        db_column="room",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubuum.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HostType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hosttypes",
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("fqdn", models.CharField(blank=True, max_length=255, null=True)),
                ("serial", models.CharField(blank=True, max_length=255, null=True)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "jack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hosts",
                        to="hubuum.jack",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hosts",
                        to="auth.group",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hosts",
                        to="hubuum.person",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hosts",
                        to="hubuum.purchaseorder",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hosts",
                        to="hubuum.room",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hosts",
                        to="hubuum.hosttype",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("hubuum.add_host", "User can add hosts"),
                    ("hubuum.change_host", "User can patch hosts"),
                    ("hubuum.view_host", "User can read the host"),
                    ("hubuum.delete_host", "User can delete the host"),
                ),
            },
        ),
    ]
