# Generated by Django 4.1.5 on 2023-01-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubuum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
