# Generated by Django 4.1.5 on 2023-02-01 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hubuum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="namespace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="hubuum.namespace"
            ),
        ),
        migrations.AlterField(
            model_name="namespace",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
