# Generated by Django 4.1.5 on 2023-01-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hubuum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="host",
            options={
                "permissions": (
                    ("edit_host", "User can edit the host, implies read capability."),
                    ("read_host", "User can read the host"),
                )
            },
        ),
    ]
