# Generated by Django 4.1.5 on 2023-01-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hubuum", "0002_alter_host_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="host",
            options={
                "permissions": (
                    ("hubuum.add_host", "User can add hosts"),
                    ("hubuum.change_host", "User can patch hosts"),
                    ("hubuum.view_host", "User can read the host"),
                    ("hubuum.delete_host", "User can delete the host"),
                )
            },
        ),
        migrations.RemoveField(
            model_name="host",
            name="owner",
        ),
        migrations.AddField(
            model_name="host",
            name="objectowner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="hosts",
                to="auth.group",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="host",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="hosts",
                to="hubuum.person",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="jack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="hosts",
                to="hubuum.jack",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="hosts",
                to="hubuum.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="hosts",
                to="hubuum.room",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="hosts",
                to="hubuum.hosttype",
            ),
        ),
        migrations.DeleteModel(
            name="DetectedHostData",
        ),
        migrations.DeleteModel(
            name="ExternalSource",
        ),
    ]
