# Generated by Django 4.1.5 on 2023-01-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubuum", "0002_alter_purchaseorder_po_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(max_length=255),
        ),
    ]
