# Generated by Django 4.1.5 on 2023-01-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hubuum", "0003_alter_purchaseorder_po_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
