# Generated by Django 4.1.5 on 2023-01-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hubuum", "0003_alter_host_options_remove_host_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="host",
            old_name="objectowner",
            new_name="owner",
        ),
    ]
